"""Add wind model to location data

Revision ID: 020596fd3b47
Revises: 150037e95645
Create Date: 2016-08-13 17:10:18.915933

"""
import webapp

# revision identifiers, used by Alembic.
revision = '020596fd3b47'
down_revision = '150037e95645'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('wind_model', webapp.models.arima_price_model.ArimaPriceModel(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'wind_model')
    ### end Alembic commands ###
