"""Add flags for scheduled weather update

Revision ID: 0305fc02f412
Revises: 9bdad6280107
Create Date: 2016-09-19 12:04:39.090512

"""

# revision identifiers, used by Alembic.
revision = '0305fc02f412'
down_revision = '9bdad6280107'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('update_at_11am', sa.Boolean(), nullable=True))
    op.add_column('locations', sa.Column('update_at_11pm', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'update_at_11pm')
    op.drop_column('locations', 'update_at_11am')
    ### end Alembic commands ###
