"""Add data source switch to windpark

Revision ID: 150037e95645
Revises: c72363e07a9a
Create Date: 2016-08-11 12:30:19.189183

"""

# revision identifiers, used by Alembic.
revision = '150037e95645'
down_revision = 'c72363e07a9a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('windparks', sa.Column('data_source', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('windparks', 'data_source')
    ### end Alembic commands ###
