"""Add generation data to wind parks

Revision ID: 4a8af19eb6fc
Revises: 305a3bcb149d
Create Date: 2016-08-03 23:09:31.046812

"""

# revision identifiers, used by Alembic.
revision = '4a8af19eb6fc'
down_revision = '305a3bcb149d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('windpark_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['windpark_id'], ['windparks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_time'), 'generation', ['time'], unique=False)
    op.create_index(op.f('ix_generation_windpark_id'), 'generation', ['windpark_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_windpark_id'), table_name='generation')
    op.drop_index(op.f('ix_generation_time'), table_name='generation')
    op.drop_table('generation')
    ### end Alembic commands ###
