"""Add wind speed distribution parameters

Revision ID: 636486d83d03
Revises: a5a48c56cbce
Create Date: 2016-07-22 23:02:41.537766

"""

# revision identifiers, used by Alembic.
revision = '636486d83d03'
down_revision = 'a5a48c56cbce'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('wspd_scale', sa.Float(), nullable=True))
    op.add_column('locations', sa.Column('wspd_shape', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'wspd_shape')
    op.drop_column('locations', 'wspd_scale')
    ### end Alembic commands ###
