"""Add fixed and rolling time ranges for weather observations

Revision ID: 64a64239efb9
Revises: 4a8af19eb6fc
Create Date: 2016-08-04 10:34:13.839876

"""

# revision identifiers, used by Alembic.
revision = '64a64239efb9'
down_revision = '4a8af19eb6fc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('history_end', sa.DateTime(), nullable=True))
    op.add_column('locations', sa.Column('history_start', sa.DateTime(), nullable=True))
    op.add_column('locations', sa.Column('time_range', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'time_range')
    op.drop_column('locations', 'history_start')
    op.drop_column('locations', 'history_end')
    ### end Alembic commands ###
