"""Add optimization input and output

Revision ID: 6c32da3e0490
Revises: 020596fd3b47
Create Date: 2016-08-21 18:47:21.152029

"""

# revision identifiers, used by Alembic.
import webapp

revision = '6c32da3e0490'
down_revision = '020596fd3b47'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('windparks', sa.Column('optimization_job', webapp.models.optimization_job.OptimizationJob(), nullable=True))
    op.add_column('windparks', sa.Column('optimization_results', webapp.models.optimization_results.OptimizationResults(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('windparks', 'optimization_results')
    op.drop_column('windparks', 'optimization_job')
    ### end Alembic commands ###
