"""Add forecast

Revision ID: 7e95c1f23234
Revises: 3aa521aa4223
Create Date: 2016-07-15 13:15:02.765139

"""

# revision identifiers, used by Alembic.
revision = '7e95c1f23234'
down_revision = '3aa521aa4223'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_location_id'), 'forecasts', ['location_id'], unique=False)
    op.create_index(op.f('ix_forecasts_time'), 'forecasts', ['time'], unique=False)
    op.create_table('hourly_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('tempm', sa.Float(), nullable=True),
    sa.Column('wspdm', sa.Float(), nullable=True),
    sa.Column('wdird', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hourly_forecasts_forecast_id'), 'hourly_forecasts', ['forecast_id'], unique=False)
    op.create_index(op.f('ix_hourly_forecasts_time'), 'hourly_forecasts', ['time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hourly_forecasts_time'), table_name='hourly_forecasts')
    op.drop_index(op.f('ix_hourly_forecasts_forecast_id'), table_name='hourly_forecasts')
    op.drop_table('hourly_forecasts')
    op.drop_index(op.f('ix_forecasts_time'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_location_id'), table_name='forecasts')
    op.drop_table('forecasts')
    ### end Alembic commands ###
