"""Add forecast error model

Revision ID: 97830d5af805
Revises: 0305fc02f412
Create Date: 2016-10-02 11:24:20.300621

"""
import webapp

# revision identifiers, used by Alembic.
revision = '97830d5af805'
down_revision = '0305fc02f412'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('forecast_error_model', webapp.models.arima_price_model.ArimaPriceModel(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'forecast_error_model')
    ### end Alembic commands ###
