"""Add wind speed from uploaded generation

Revision ID: 97d9d62ddea2
Revises: 97830d5af805
Create Date: 2016-10-19 13:59:01.426377

"""

# revision identifiers, used by Alembic.
revision = '97d9d62ddea2'
down_revision = '97830d5af805'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation', sa.Column('wind_speed', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation', 'wind_speed')
    ### end Alembic commands ###
