"""Add unfiltered wind speed column

Revision ID: a5a48c56cbce
Revises: 6440a41d0a8e
Create Date: 2016-07-22 14:24:36.041955

"""

# revision identifiers, used by Alembic.
revision = 'a5a48c56cbce'
down_revision = '6440a41d0a8e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('wspdm_raw', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'wspdm_raw')
    ### end Alembic commands ###
