"""Add windpark-turbines relationship

Revision ID: c72363e07a9a
Revises: c4010ede3daa
Create Date: 2016-08-09 11:36:52.797543

"""

# revision identifiers, used by Alembic.
revision = 'c72363e07a9a'
down_revision = 'c4010ede3daa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('windpark_turbines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('windpark_id', sa.Integer(), nullable=True),
    sa.Column('turbine_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['turbine_id'], ['turbines.id'], ),
    sa.ForeignKeyConstraint(['windpark_id'], ['windparks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_windpark_turbines_windpark_id'), 'windpark_turbines', ['windpark_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_windpark_turbines_windpark_id'), table_name='windpark_turbines')
    op.drop_table('windpark_turbines')
    ### end Alembic commands ###
