"""Add all sorts of market prices

Revision ID: ea2ff712150d
Revises: 552a52533dac
Create Date: 2016-07-27 21:45:28.481149

"""

# revision identifiers, used by Alembic.
revision = 'ea2ff712150d'
down_revision = '552a52533dac'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historical_prices', sa.Column('lambdaA', sa.Float(), nullable=True))
    op.add_column('historical_prices', sa.Column('lambdaMinus', sa.Float(), nullable=True))
    op.add_column('historical_prices', sa.Column('lambdaPlus', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historical_prices', 'lambdaPlus')
    op.drop_column('historical_prices', 'lambdaMinus')
    op.drop_column('historical_prices', 'lambdaA')
    ### end Alembic commands ###
